## 🏋️🐼 Práctica de Data cleaning (pandas) 

Cómo usar este cuaderno:
1. Completa el código en cada reto.
2. Ejecuta el check si existe.
3. Si algo falla, corrige y vuelve a intentar, ¡sin miedo a destruir !

¡Vamos a ello! 

Javi lleva meses registrando sus entrenamientos en un archivo.
El problema: **lo hizo sin ningún orden**. 😅

Fechas raras, datos que faltan, valores imposibles, duplicados...

Nuestra misión: **limpiar el dataset** para que se pueda analizar correctamente. 💪

---

### ¿Qué vamos a practicar?

| Paso | Concepto |
|------|----------|
| 1 | Cargar un CSV con pandas |
| 2 | Explorar y entender los datos |
| 3 | Detectar y eliminar duplicados |
| 4 | Manejar valores nulos |
| 5 | Limpiar y convertir fechas |
| 6 | Detectar y corregir valores erróneos |
| 7 | Análisis final |

> 🌱 **Nivel:** Principiantes del bootcamp  
> ⏱️ **Tiempo estimado:** 50 minutos  
> 🐼 **Librería:** `pandas`

**Nombre:** __SARA BAILON SARMIENTO__  **Fecha:** __03/03/2026

---
## 📦 Paso 0 — Importar pandas

Siempre empezamos importando la librería que vamos a usar.

In [5]:
# Ejecuta esta celda (Shift + Enter)
import pandas as pd

print('✅ pandas listo, versión:', pd.__version__)

✅ pandas listo, versión: 3.0.1

---
## 📂 Paso 1 — Cargar el dataset

El dataset está guardado en un archivo llamado `data.csv`.
Vamos a cargarlo en un DataFrame.

### Ejercicio 1
Carga el archivo `data.csv` usando `pd.read_csv()` y guárdalo en una variable llamada `df`. Luego muéstralo.

> 💡 **Pista:** `pd.read_csv('nombre_del_archivo.csv')`

In [4]:
# ✏️ Carga el CSV aquí
dataset = "dataset_gimnasio.csv"
df = pd.read_csv(dataset)
df

# Muestra el DataFrame

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

### 🤔 Pregunta 1
Observa el DataFrame. Anota todos los problemas que veas (doble clic para editar):

| # | Columna | Problema que veo |
|---|---------|------------------|
| 1 |DURATION | Fila 7: 450      |
| 2 |DATA     | Fila 22: NaN     |
| 3 |CALORIES | Fila 18: NaN     |
| 4 |CALORIES | Fila 28: NaN     |
| 5 |DATA     | Fila 26: 20201226|

---
## 🔍 Paso 2 — Explorar los datos

Antes de limpiar, hay que **entender bien** lo que tenemos.

### Ejercicio 2.1 — ¿Cuántos registros hay?
Muestra las **dimensiones** del DataFrame (filas y columnas).

> 💡 **Pista:** `.shape`

In [7]:
print("Dimensiones del dataset:", df.shape)

Dimensiones del dataset: (32, 5)

### Ejercicio 2.2 — ¿Qué tipo de datos tiene cada columna?

> 💡 **Pista:** `.dtypes`  
> Recuerda: `object`= texto, `int64` = entero, `float64` = decimal

In [8]:
# ✏️ Tu código aquí
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

### Ejercicio 2.3 — ¿Cuántos valores faltan?
Cuenta los valores nulos en cada columna.

> 💡 **Pista:** `.isnull().sum()`

In [9]:
# ✏️ Tu código aquí
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

### Ejercicio 2.4 — Estadísticas básicas
Muestra un resumen estadístico del DataFrame (mínimo, máximo, media...).

> 💡 **Pista:** `.describe()`

In [10]:
# ✏️ Tu código aquí
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

### 🤔 Pregunta 2
Fíjate en el valor **máximo de `Duration`**. ¿Te parece normal? ¿Qué crees que pasó?

_(escribe tu respuesta aquí)_
# Se ha colado un dato erroneo.

---
## 🎯 Paso 3 — Eliminar duplicados

Parece que algún entrenamiento se registró dos veces.

### Ejercicio 3.1 — Encontrar los duplicados
Muestra las filas que están repetidas.

> 💡 **Pista:** `df[df.duplicated(keep=False)]`  
> `keep=False` marca **todas** las copias como duplicadas

In [22]:
# ✏️ Muestra las filas duplicadas
df[df.duplicated(keep=False)]

    Duration          Date  Pulse  Maxpulse  Calories
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7

### Ejercicio 3.2 — Eliminar los duplicados
Quédate solo con la primera aparición y reinicia el índice.

> 💡 **Pistas:**
> - `.drop_duplicates()` elimina duplicados
> - `.reset_index(drop=True)` reinicia el índice
> - Recuerda guardar: `df = ...`

In [56]:
# ✏️ Elimina duplicados y reinicia el índice
df_nueva = df.drop_duplicates()
df_nueva = df_nueva.reset_index(drop=True)

print('Filas después de eliminar duplicados:', len(df_nueva))

Filas después de eliminar duplicados: 31

---
## 🕳️ Paso 4 — Manejar valores nulos

Tenemos valores nulos en `Date` y `Calories`. Los trataremos de forma diferente.

### Ejercicio 4.1 — Ver las filas con nulos
Muestra solo las filas que tienen algún valor nulo.

> 💡 **Pista:** `df[df.isnull().any(axis=1)]`  
> `axis=1` significa "busca en cada fila"

In [57]:
# ✏️ Muestra las filas con nulos
df[df.isnull().any(axis=1)]

    Duration          Date  Pulse  Maxpulse  Calories
18        45  '2020/12/18'     90       112       NaN
22        45           NaN    100       119     282.0
28        60  '2020/12/28'    103       132       NaN

### Ejercicio 4.2 — Rellenar Calories con la media
Rellena los huecos de `Calories` con la media de esa columna, redondeada a 1 decimal.

> 💡 **Pistas:**
> - Calcula primero: `df['Calories'].mean()`
> - Redondea: `round(media, 1)`
> - Rellena: `.fillna(valor)`

In [85]:
# ✏️ Calcula la media e imprímela
media = df_nueva['Calories'].mean()
media = round(media, 1)
# ✏️ Rellena los huecos de Calories

df_nueva['Calories'] = df_nueva['Calories'].fillna(media)
df_nueva['Calories'] = df_nueva['Calories'].round(1)

print('Nulos en Calories:', df_nueva['Calories'].isnull().sum())

Nulos en Calories: 0

### Ejercicio 4.3 — Eliminar la fila con Date nula
La fila que no tiene fecha no nos sirve. Elimínala y reinicia el índice.

> 💡 **Pistas:**
> - `.dropna(subset=['Date'])` elimina filas con nulo en Date
> - `.reset_index(drop=True)`

In [61]:
# ✏️ Elimina la fila sin fecha
df_nueva = df_nueva.dropna(subset=['Date'])
df_nueva = df_nueva.reset_index(drop=True)
print('Filas restantes:', len(df_nueva))
print('Nulos totales:', df_nueva.isnull().sum().sum())

Filas restantes: 30
Nulos totales: 2

---
## 📅 Paso 5 — Limpiar la columna de fechas

La columna `Date` tiene un problema: la mayoría de fechas tienen comillas (`'2020/12/01'`) y **una** tiene un formato completamente diferente (`20201226`).

### Ejercicio 5.1 — Ver los valores únicos de Date
Imprime todos los valores de la columna `Date` para ver el problema.

> 💡 **Pista:** `df['Date'].tolist()`

In [29]:
# ✏️ Muestra todos los valores de Date
df['Date'].tolist()

["'2020/12/01'",
 "'2020/12/02'",
 "'2020/12/03'",
 "'2020/12/04'",
 "'2020/12/05'",
 "'2020/12/06'",
 "'2020/12/07'",
 "'2020/12/08'",
 "'2020/12/09'",
 "'2020/12/10'",
 "'2020/12/11'",
 "'2020/12/12'",
 "'2020/12/12'",
 "'2020/12/13'",
 "'2020/12/14'",
 "'2020/12/15'",
 "'2020/12/16'",
 "'2020/12/17'",
 "'2020/12/18'",
 "'2020/12/19'",
 "'2020/12/20'",
 "'2020/12/21'",
 nan,
 "'2020/12/23'",
 "'2020/12/24'",
 "'2020/12/25'",
 '20201226',
 "'2020/12/27'",
 "'2020/12/28'",
 "'2020/12/29'",
 "'2020/12/30'",
 "'2020/12/31'"]

### Ejercicio 5.2 — Eliminar las comillas
Elimina las comillas simples (`'`) que rodean las fechas.

> 💡 **Pista:** `.str.replace("'", '', regex=False)`

In [66]:
# ✏️ Elimina las comillas de la columna Date
df_nueva['Date'] = (
    df_nueva['Date']
    .astype(str)
    .str.strip()
    .str.replace('"', '', regex=False)
    .str.replace("'", '', regex=False)
)
print(df_nueva['Date'].tolist())

['2020/12/01', '2020/12/02', '2020/12/03', '2020/12/04', '2020/12/05', '2020/12/06', '2020/12/07', '2020/12/08', '2020/12/09', '2020/12/10', '2020/12/11', '2020/12/12', '2020/12/13', '2020/12/14', '2020/12/15', '2020/12/16', '2020/12/17', '2020/12/18', '2020/12/19', '2020/12/20', '2020/12/21', '2020/12/23', '2020/12/24', '2020/12/25', '20201226', '2020/12/27', '2020/12/28', '2020/12/29', '2020/12/30', '2020/12/31']

### Ejercicio 5.3 — Convertir al tipo fecha
Convierte `Date` al tipo de dato `datetime` de pandas.

> 💡 **Pista:** `pd.to_datetime(df['Date'], infer_datetime_format=True)`  
> Con `infer_datetime_format=True` pandas intenta detectar el formato solo

In [67]:
# ✏️ Convierte Date a datetime
df_nueva['Date'] = pd.to_datetime(df_nueva['Date'], dayfirst=True, format='mixed')

print(df_nueva['Date'])

0    2020-01-12
1    2020-02-12
2    2020-03-12
3    2020-04-12
4    2020-05-12
5    2020-06-12
6    2020-07-12
7    2020-08-12
8    2020-09-12
9    2020-10-12
10   2020-11-12
11   2020-12-12
12   2020-12-13
13   2020-12-14
14   2020-12-15
15   2020-12-16
16   2020-12-17
17   2020-12-18
18   2020-12-19
19   2020-12-20
20   2020-12-21
21   2020-12-23
22   2020-12-24
23   2020-12-25
24   2020-12-26
25   2020-12-27
26   2020-12-28
27   2020-12-29
28   2020-12-30
29   2020-12-31
Name: Date, dtype: datetime64[us]

---
## 🚨 Paso 6 — Detectar y corregir valores erróneos

Cuando revisaste el `.describe()`, ¿viste algo raro en `Duration`?
Hay un entrenamiento registrado con **450 minutos** (¡7 horas y media!) 😱

### Ejercicio 6.1 — Ver la fila problemática
Muestra la fila donde `Duration` es mayor que 120 minutos.

> 💡 **Pista:** `df[df['Duration'] > 120]`

In [68]:
# ✏️ Muestra las filas con Duration > 120
df_nueva[df_nueva['Duration'] > 120]

   Duration       Date  Pulse  Maxpulse  Calories
7       450 2020-08-12    104       134     253.3

### 🤔 Pregunta 3
El valor es `450`. ¿Qué crees que pasó? Marca la opción que te parece más probable:

- [ ] Fue un error tipográfico (quería escribir `45`)
- [ ] El entrenamiento duró de verdad 450 minutos
- [ ] El dato proviene de otra unidad de medida

_(escribe tu razonamiento aquí)_

# Posiblemente sea un error tipografico al escribir, pero no sabemos cual sera el valor original (tambien puede ser 50 y que se haya colado el 4)

### Ejercicio 6.2 — Corregir el valor
Reemplaza el valor `450` por `45` en la columna `Duration`.

> 💡 **Pista:** `df['Duration'] = df['Duration'].replace(450, 45)`

In [70]:
# ✏️ Corrige el valor 450 → 45
df_nueva['Duration'] = df_nueva['Duration'].replace(450, 45)

print('Duración máxima ahora:', df_nueva['Duration'].max(), 'minutos')

Duración máxima ahora: 60 minutos

### Ejercicio 6.3 — Revisar Maxpulse
Hay una fila donde el pulso máximo (`Maxpulse`) es **menor** que el pulso normal (`Pulse`). ¡Eso es imposible fisiológicamente!

Encuéntrala.

> 💡 **Pista:** `df[df['Maxpulse'] < df['Pulse']]`

In [71]:
# ✏️ Encuentra la fila donde Maxpulse < Pulse
df_nueva[df_nueva['Maxpulse'] < df_nueva['Pulse']]

    Duration       Date  Pulse  Maxpulse  Calories
21        60 2020-12-23    130       101     300.0

### Ejercicio 6.4 — Eliminar la fila incorrecta
Esa fila tiene datos imposibles. Elimínala y reinicia el índice.

> 💡 **Pista:** quédate con las filas donde `Maxpulse >= Pulse`  
> `df = df[df['Maxpulse'] >= df['Pulse']].reset_index(drop=True)`

In [73]:
# ✏️ Elimina la fila con Maxpulse < Pulse
df_nueva = df_nueva[df_nueva['Maxpulse'] >= df_nueva['Pulse']].reset_index(drop=True)

print('Filas en el dataset limpio:', len(df_nueva))

Filas en el dataset limpio: 29

---
## 🏆 Paso 7 — Dataset limpio y análisis final

### Ejercicio 7.1 — Ver el resultado final
Muestra el DataFrame limpio completo.

In [86]:
# ✏️ Muestra el DataFrame final
df_nueva

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-01-12    110       130     409.1
1         60 2020-02-12    117       145     479.0
2         60 2020-03-12    103       135     340.0
3         45 2020-04-12    109       175     282.4
4         45 2020-05-12    117       148     406.0
5         60 2020-06-12    102       127     300.0
6         60 2020-07-12    110       136     374.0
7         45 2020-08-12    104       134     253.3
8         30 2020-09-12    109       133     195.1
9         60 2020-10-12     98       124     269.0
10        60 2020-11-12    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-13    106       128     345.3
13        60 2020-12-14    104       132     379.3
14        60 2020-12-15     98       123     275.0
15        60 2020-12-16     98       120     215.2
16        60 2020-12-17    100       120     300.0
17        45 2020-12-18     90       112     307.7
18        60 2020-12-19    103       123     323.0
19        45 2020-12-20     97       125     243.0
20        60 2020-12-21    108       131     364.2
21        45 2020-12-24    105       132     246.0
22        60 2020-12-25    102       126     334.5
23        60 2020-12-26    100       120     250.0
24        60 2020-12-27     92       118     241.0
25        60 2020-12-28    103       132     307.7
26        60 2020-12-29    100       132     280.0
27        60 2020-12-30    102       129     380.3
28        60 2020-12-31     92       115     243.0

### Ejercicio 7.2 — Preguntas de análisis
Usa el DataFrame limpio para responder:

In [88]:
# 🔥 ¿Cuántas calorías quemó en total?
# Pista: .sum()
total_calorias = df_nueva['Calories'].sum()
print(f"El numero total de calorias quemadas es: {total_calorias}")

El numero total de calorias quemadas es: 8923.099999999999

In [91]:
# 💓 ¿Cuál fue el pulso medio durante los entrenamientos?
# Pista: .mean() y round()
pulso_medio = df_nueva["Pulse"].sum() / len(df_nueva["Pulse"])
print(f"El pulso medio durante los entrenamientos fue: {pulso_medio.round()}")

El pulso medio durante los entrenamientos fue: 103.0

In [97]:
# 🏅 ¿En qué fecha quemó más calorías?
# Pista: filtra la fila con el máximo de Calories usando .idxmax()
# df.loc[df['Calories'].idxmax()]
fila_max = df_nueva['Calories'].idxmax()
fila_mas_calorias = df_nueva.loc[fila_max]

print(f"La fecha de entrenamiento con más consumo de calorias es: {fila_mas_calorias["Date"]}")

La fecha de entrenamiento con más consumo de calorias es: 2020-02-12 00:00:00

In [99]:
# ⏱️ ¿Cuántos entrenamientos duraron exactamente 60 minutos?
duracion_60 = len(df_nueva[df_nueva['Duration'] == 60])

print(f"Hay {duracion_60} entrenamientos con una duración de 60 minutos")

Hay 22 entrenamientos con una duración de 60 minutos

---
## 📝 Resumen final — Completa la tabla

Rellena con lo que has aprendido hoy (doble clic para editar):

| Problema encontrado | Método de pandas que usé |
|---------------------|---------------------------|
| Cargar un archivo CSV | pd.read_csv(dataset) |
| Ver dimensiones del DataFrame | df.shape |
| Ver tipos de datos | df.dtype|
| Contar valores nulos | df.isnull().sum() |
| Ver estadísticas básicas | df.describe() |
| Eliminar filas duplicadas | df.drop_duplicates() |
| Rellenar valores nulos con la media | df['Calories'].fillna(media) |
| Eliminar filas con nulos | df.dropna(subset=['Date'])|
| Limpiar texto en una columna | df['Date'].tolist() |
| Convertir texto a fecha | pd.to_datetime(df_nueva['Date']) |
| Corregir un valor erróneo | df['Duration'] = df['Duration'].replace(450, 45) |
| Filtrar filas por condición | df_nueva[df_nueva['Duration'] > 120] |

---
### 💪 ¡El dataset está limpio y listo para analizar. Buen trabajo!