In [ ]:
# Imagina que trabajas con un gimnasio que te envía un archivo CSV llamado . El archivo contiene registros de entrenamientos, pero está lleno de problemas típicos: duplicados, fechas mal formateadas, valores nulos y algunos errores de entrada.
# Tu misión es limpiar el dataset y obtener un pequeño análisis final.

In [2]:
# PASO 1: Hay que importar la libreria PANDAS para poder usarla durante el ejercicio y ver el archivo en este ejercicio.

import pandas as pd

print('Pandas listo, versión:', pd.__version__)

Pandas listo, versión: 3.0.1

In [4]:
# PASO 2: Ahora tenemos que ver la tabla en pantalla. Para ello, usamos el metodo "pd.read_csv": 

tabla = "gimnasio_clientes.csv"
datos = pd.read_csv(tabla)
datos

          Date  Duration  Calories
0  2024/01/03'        60     409.0
1   2024/01/03        60     409.0
2  2024/01/04'        45     479.0
3  2024/01/05'       282       4.0
4  2024/01/06'        30       NaN
5  2024/13/01'        50     300.0
6  2024/01/07'       -20     150.0
7  2024/01/08'        60     409.0

In [5]:
# PASO 3: ¿Y que datos nos han dado? ¿Que tenemos que analizar?

datos.dtypes

Date            str
Duration      int64
Calories    float64
dtype: object

In [6]:
# PASO 4: Sabiendo que tipo de datos tenemos, vamos a mirar la tabla para ver si hay algún dato que nos llame la atención:

    # En este caso, llama la atencion las ' despues de las fechas, datos anomalos en la duracion y en las calorias.

In [7]:
# PASO 5: ¿Cuantos entrenamientos tenemos en total? --> Tenemos que saber de donde partimos.

print(f"En total, con datos invalidos, tenemos una grafica del tamaño de: {datos.shape} (filas,columnas)")

En total, con datos invalidos, tenemos una grafica del tamaño de: (8, 3) (filas,columnas)

In [8]:
# PASO 6: Ahora vamos a sacar estadísticas para comprobar si algo más nos llama la atención:

datos.describe()

         Duration    Calories
count    8.000000    7.000000
mean    70.875000  308.571429
std     89.413066  171.894209
min    -20.000000    4.000000
25%     41.250000  225.000000
50%     55.000000  409.000000
75%     60.000000  409.000000
max    282.000000  479.000000

In [10]:
# Lo que nos indica que:
    # Hay 8 datos validos de la columna de duración y 7 en la columna de calorias --> Sobra un dato de la primera columna.
    # Tenemos un minimo de -20 en la duración.
    # Tenemos un dato muy extremo de 4 calorias y otro de 7 calorias. Eso se hace pestañeando, asi que lo voy a considerar error. 
    # Tenemos un dato de una duración de 282 minutos entrenando (son unas 5h entrenando). También es un valor muy extremo.

In [13]:
# PASO 7: Vamos a empezar a analizar la tabla, ya en serio. Lo primero, le vamos a decir que busque datos nulos.

datos.isnull().sum()

Date        0
Duration    0
Calories    1
dtype: int64

In [15]:
# PASO 8: Tenemos un dato nulo en la columna de calorias. Como no nos interesa trabajar con él, vamos a eliminarlo de la tabla:

    # Primero, tenemos que localizar en que fila se encuentra ese dato nulo:

datos[datos.isnull().any(axis=1)]

# Aclaración: 
    #  Con el comando -datos.isnull()- estás diciendo: "Crea un DataFrame de True/False indicando dónde hay nulos"
    #  Con el comando -any(axis=1)- estás diciendo: "Para cada fila, dime si alguna de sus columnas tiene un valor nulo"
    #  Con los dos juntos, estas diciendo: "Revisa cada fila (por eso axis=1) y devuelve True si esa fila tiene al menos un nulo"

          Date  Duration  Calories
4  2024/01/06'        30       NaN

In [16]:
    # Segundo, ya sabemos que está en la fila 4. Ahora vamos a cargarnosla:

datos = datos.dropna(subset=['Calories'])

In [17]:
    # Tercero y último, vamos a reiniciar el dataset sin ese valor nulo:

datos = datos.reset_index(drop=True)

In [18]:
    # Y claro, darle a imprimir para ver que tenemos:

print('Filas restantes:', len(datos))
print('Nulos totales:', datos.isnull().sum().sum())
datos

Filas restantes: 7
Nulos totales: 0

          Date  Duration  Calories
0  2024/01/03'        60     409.0
1   2024/01/03        60     409.0
2  2024/01/04'        45     479.0
3  2024/01/05'       282       4.0
4  2024/13/01'        50     300.0
5  2024/01/07'       -20     150.0
6  2024/01/08'        60     409.0

In [20]:
# PASO 9: Ahora que tenemos la tabla sin valores nulos, vamos a corregir las fechas, poniendo todas en el mismo formato:

    # En primer lugar, vamos a sacar toda la columna de "Fechas":

datos['Date'].tolist()

["2024/01/03'",
 '2024/01/03',
 "2024/01/04'",
 "2024/01/05'",
 "2024/13/01'",
 "2024/01/07'",
 "2024/01/08'"]

In [21]:
    # En segundo lugar, vamos a eliminar las comillas que nos sobren de las fechas:

datos['Date'] = (
    datos['Date']
    .str.replace("'", '', regex=False)
)
print(datos['Date'].tolist())

['2024/01/03', '2024/01/03', '2024/01/04', '2024/01/05', '2024/13/01', '2024/01/07', '2024/01/08']

In [23]:
# Para asegurarnos, volvemos a llamar a la tabla a ver como queda:

datos

         Date  Duration  Calories
0  2024/01/03        60     409.0
1  2024/01/03        60     409.0
2  2024/01/04        45     479.0
3  2024/01/05       282       4.0
4  2024/13/01        50     300.0
5  2024/01/07       -20     150.0
6  2024/01/08        60     409.0

In [ ]:
# PASO 10: Ahora que tenemos la tabla limpia, vamos a buscar duplicados:

datos[datos.duplicated(keep=False)]

         Date  Duration  Calories
0  2024/01/03        60     409.0
1  2024/01/03        60     409.0

In [ ]:
# Tenemos 2 duplicados! Vamos a eliminar uno de ellos de la lista:

datos = datos.drop_duplicates()

In [26]:
# ¿Como ha quedado la tabla ahora que hemos borrado otro dato?

datos

         Date  Duration  Calories
0  2024/01/03        60     409.0
2  2024/01/04        45     479.0
3  2024/01/05       282       4.0
4  2024/13/01        50     300.0
5  2024/01/07       -20     150.0
6  2024/01/08        60     409.0

In [27]:
# PASO 11: Vamos a poner todas las fechas en el mismo formato para manejar mejor los datos:

datos['Date'] = pd.to_datetime(datos['Date'], dayfirst=True, format='mixed')

print(datos['Date'])

0   2024-03-01
2   2024-04-01
3   2024-05-01
4   2024-01-13
5   2024-07-01
6   2024-08-01
Name: Date, dtype: datetime64[us]

In [ ]:
# PASO 12: Seguimos teniendo datos anómalos en la columna de "duration", ¿Que hacemos con ellos?

    # Lo primero es localizar los valores extremos que pasen de 2h de entrenamiento:

datos[datos['Duration'] > 120]

        Date  Duration  Calories
3 2024-05-01       282       4.0

In [ ]:
    # Este dato, posiblemente sea un error, ya que no pueden ser 4 calorias en 282 minutos. Como ambos valores están mal, los voy a eliminar también.

datos = datos[datos['Duration'] <= 120]

    # Con esta formula, mantiene en la tabla los resultados que entren dentro de la condición

In [34]:
    # Comprobamos como queda la tabla: 

datos

        Date  Duration  Calories
0 2024-03-01        60     409.0
2 2024-04-01        45     479.0
4 2024-01-13        50     300.0
5 2024-07-01       -20     150.0
6 2024-08-01        60     409.0

In [ ]:
    # Vamos a buscar los resultados que estén por debajo de 10 minutos (un entrenamiento de menos de 10 minutos NO es un entrenamiento):

datos[datos['Duration'] < 10]

        Date  Duration  Calories
5 2024-07-01       -20     150.0

In [38]:
    # En este caso, vamos a cambiar la duración de -20 a 20. 

datos['Duration'] = datos['Duration'].replace(-20, 20)

In [39]:
    # Volvermos a sacar la tabla para comprobar que está corregido:

datos

        Date  Duration  Calories
0 2024-03-01        60     409.0
2 2024-04-01        45     479.0
4 2024-01-13        50     300.0
5 2024-07-01        20     150.0
6 2024-08-01        60     409.0

In [ ]:
# Ya tenemos la tabla limpia

    # Estas son las fórmulas que no he utilizado pero que puedo necesitar en un futuro:

# Rellenar datos: 
    """# ✏️ Calcula la media e imprímela
media = df_nueva['Calories'].mean()
media = round(media, 1)
# ✏️ Rellena los huecos de Calories

df_nueva['Calories'] = df_nueva['Calories'].fillna(media)
df_nueva['Calories'] = df_nueva['Calories'].round(1)

print('Nulos en Calories:', df_nueva['Calories'].isnull().sum())"""

# Filtrar filas:

    """# 🏅 ¿En qué fecha quemó más calorías?
# Pista: filtra la fila con el máximo de Calories usando .idxmax()
# df.loc[df['Calories'].idxmax()]
fila_max = df_nueva['Calories'].idxmax()
fila_mas_calorias = df_nueva.loc[fila_max]"""